services:
  - type: web
    name: coderecet-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase-adminsdk.json
